#!/usr/bin/env php
<?php

// +----------------------------------------------------------------------
// | 版权所有 2014~2024 魏东 [ 54928382@qq.com]
// +----------------------------------------------------------------------

use think\admin\service\RuntimeService;

// 加载基础文件
require __DIR__ . '/vendor/autoload.php';

// 命令行应用初始化
RuntimeService::doConsoleInit();